# Generated by Django 3.2.17 on 2024-02-24 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20240224_1422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boletim',
            options={},
        ),
        migrations.RemoveField(
            model_name='boletim',
            name='aprovado',
        ),
        migrations.RemoveField(
            model_name='boletim',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='boletim',
            name='nota',
        ),
        migrations.AlterField(
            model_name='cursos',
            name='curso',
            field=models.CharField(max_length=150, verbose_name='Curso ou Matéria'),
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.capitulos')),
            ],
        ),
        migrations.AddField(
            model_name='boletim',
            name='notas',
            field=models.ManyToManyField(to='core.Nota'),
        ),
    ]
