# Generated by Django 3.2.17 on 2024-02-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20240224_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusuario',
            name='turma',
        ),
        migrations.AddField(
            model_name='customusuario',
            name='turmas',
            field=models.ManyToManyField(related_name='alunos', to='core.Turmas', verbose_name='Turmas'),
        ),
    ]
