# Generated by Django 3.2.17 on 2024-02-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20240226_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusuario',
            name='turmas',
            field=models.ManyToManyField(blank=True, null=True, related_name='alunos', to='core.Turmas', verbose_name='Turmas'),
        ),
    ]
