# Generated by Django 3.2.17 on 2024-02-27 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_customusuario_turmas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoaulas',
            name='aula',
        ),
        migrations.AddField(
            model_name='videoaulas',
            name='tema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.temas'),
        ),
    ]
