# Generated by Django 3.2.17 on 2024-03-01 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20240227_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notas',
            name='capitulo',
        ),
        migrations.AddField(
            model_name='notas',
            name='aula',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.aulas'),
            preserve_default=False,
        ),
    ]
