# Generated by Django 3.2.17 on 2024-03-01 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20240301_1244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boletim',
            options={'verbose_name': 'Boletim', 'verbose_name_plural': 'Boletins'},
        ),
        migrations.AlterModelOptions(
            name='notas',
            options={'verbose_name': 'Nota', 'verbose_name_plural': 'Notas'},
        ),
        migrations.AddField(
            model_name='boletim',
            name='aula',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.aulas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boletim',
            name='capitulo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.capitulos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boletim',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.cursos'),
            preserve_default=False,
        ),
    ]
