# Generated by Django 3.2.17 on 2024-03-06 16:30

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20240301_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questoes',
            name='apostila',
        ),
        migrations.AlterField(
            model_name='apostilas',
            name='arquivo',
            field=models.FileField(upload_to=core.models.get_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), core.models.validate_file_size], verbose_name='Arquivo'),
        ),
    ]
