# Generated by Django 3.2.17 on 2024-04-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20240306_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricoes',
            name='codigo_pg',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código Pagamento'),
        ),
    ]
