# Generated by Django 3.2.17 on 2024-04-26 20:30

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_inscricoes_codigo_pg'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoaulas',
            name='video_arquivo',
            field=models.FileField(blank=True, null=True, upload_to=core.models.get_file_path, verbose_name='Arquivo de Vídeo'),
        ),
    ]
