# Generated by Django 3.2.17 on 2024-05-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_videoaulas_video_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresas',
            name='comissao_percentual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Percentual de Comissão'),
        ),
    ]
