# Generated by Django 3.2.17 on 2024-05-17 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_empresas_comissao_percentual'),
    ]

    operations = [
        migrations.CreateModel(
            name='Positivador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField(auto_now_add=True, verbose_name='Data do Pagamento')),
                ('receita_parceiro', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Valor da Comissão')),
                ('receita_matriz', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Receita Sede')),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cursos')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.empresas')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Positivador',
                'verbose_name_plural': 'Positivador',
            },
        ),
    ]
