# Generated by Django 3.2.17 on 2024-05-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_positivador'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='carga_horaria',
            field=models.IntegerField(blank=True, null=True, verbose_name='Carga horária'),
        ),
    ]
