# Generated by Django 3.2.17 on 2024-05-18 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_cursos_carga_horaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_conclusao', models.DateField(auto_now_add=True, verbose_name='Data de Conclusão')),
                ('pdf', models.FileField(upload_to='certificados/')),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('codigo_autenticacao', models.CharField(max_length=25, verbose_name='Código de autenticação')),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cursos', models.ManyToManyField(to='core.Cursos')),
            ],
        ),
    ]
