# Generated by Django 3.2.17 on 2024-05-21 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_certificados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificados',
            name='pdf',
        ),
        migrations.AddField(
            model_name='cursos',
            name='conteudoProgramatico',
            field=models.TextField(blank=True, null=True, verbose_name='Conteúdo Programático'),
        ),
        migrations.AlterField(
            model_name='boletim',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='boletim',
            name='aula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.aulas'),
        ),
        migrations.AlterField(
            model_name='boletim',
            name='capitulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.capitulos'),
        ),
        migrations.AlterField(
            model_name='boletim',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cursos'),
        ),
    ]
